<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<?codewarrior exportversion="1.0.1" ideversion="5.0" ?>

<!DOCTYPE PROJECT [
<!ELEMENT PROJECT (TARGETLIST, TARGETORDER, GROUPLIST, DESIGNLIST?)>
<!ELEMENT TARGETLIST (TARGET+)>
<!ELEMENT TARGET (NAME, SETTINGLIST, FILELIST?, LINKORDER?, SEGMENTLIST?, OVERLAYGROUPLIST?, SUBTARGETLIST?, SUBPROJECTLIST?, FRAMEWORKLIST?, PACKAGEACTIONSLIST?)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT USERSOURCETREETYPE (#PCDATA)>
<!ELEMENT PATH (#PCDATA)>
<!ELEMENT FILELIST (FILE*)>
<!ELEMENT FILE (PATHTYPE, PATHROOT?, ACCESSPATH?, PATH, PATHFORMAT?, ROOTFILEREF?, FILEKIND?, FILEFLAGS?)>
<!ELEMENT PATHTYPE (#PCDATA)>
<!ELEMENT PATHROOT (#PCDATA)>
<!ELEMENT ACCESSPATH (#PCDATA)>
<!ELEMENT PATHFORMAT (#PCDATA)>
<!ELEMENT ROOTFILEREF (PATHTYPE, PATHROOT?, ACCESSPATH?, PATH, PATHFORMAT?)>
<!ELEMENT FILEKIND (#PCDATA)>
<!ELEMENT FILEFLAGS (#PCDATA)>
<!ELEMENT FILEREF (TARGETNAME?, PATHTYPE, PATHROOT?, ACCESSPATH?, PATH, PATHFORMAT?)>
<!ELEMENT TARGETNAME (#PCDATA)>
<!ELEMENT SETTINGLIST ((SETTING|PANELDATA)+)>
<!ELEMENT SETTING (NAME?, (VALUE|(SETTING+)))>
<!ELEMENT PANELDATA (NAME, VALUE)>
<!ELEMENT VALUE (#PCDATA)>
<!ELEMENT LINKORDER (FILEREF*)>
<!ELEMENT SEGMENTLIST (SEGMENT+)>
<!ELEMENT SEGMENT (NAME, ATTRIBUTES?, FILEREF*)>
<!ELEMENT ATTRIBUTES (#PCDATA)>
<!ELEMENT OVERLAYGROUPLIST (OVERLAYGROUP+)>
<!ELEMENT OVERLAYGROUP (NAME, BASEADDRESS, OVERLAY*)>
<!ELEMENT BASEADDRESS (#PCDATA)>
<!ELEMENT OVERLAY (NAME, FILEREF*)>
<!ELEMENT SUBTARGETLIST (SUBTARGET+)>
<!ELEMENT SUBTARGET (TARGETNAME, ATTRIBUTES?, FILEREF?)>
<!ELEMENT SUBPROJECTLIST (SUBPROJECT+)>
<!ELEMENT SUBPROJECT (FILEREF, SUBPROJECTTARGETLIST)>
<!ELEMENT SUBPROJECTTARGETLIST (SUBPROJECTTARGET*)>
<!ELEMENT SUBPROJECTTARGET (TARGETNAME, ATTRIBUTES?, FILEREF?)>
<!ELEMENT FRAMEWORKLIST (FRAMEWORK+)>
<!ELEMENT FRAMEWORK (FILEREF, DYNAMICLIBRARY?, VERSION?)>
<!ELEMENT PACKAGEACTIONSLIST (PACKAGEACTION+)>
<!ELEMENT PACKAGEACTION (#PCDATA)>
<!ELEMENT LIBRARYFILE (FILEREF)>
<!ELEMENT VERSION (#PCDATA)>
<!ELEMENT TARGETORDER (ORDEREDTARGET|ORDEREDDESIGN)*>
<!ELEMENT ORDEREDTARGET (NAME)>
<!ELEMENT ORDEREDDESIGN (NAME, ORDEREDTARGET+)>
<!ELEMENT GROUPLIST (GROUP|FILEREF)*>
<!ELEMENT GROUP (NAME, (GROUP|FILEREF)*)>
<!ELEMENT DESIGNLIST (DESIGN+)>
<!ELEMENT DESIGN (NAME, DESIGNDATA)>
<!ELEMENT DESIGNDATA (#PCDATA)>
]>

<PROJECT>
    <TARGETLIST>
        <TARGET>
            <NAME>Win32 C DLL Debug</NAME>
            <SETTINGLIST>

                <!-- Settings for "Source Trees" panel -->
                <SETTING><NAME>UserSourceTrees</NAME><VALUE></VALUE></SETTING>

                <!-- Settings for "Access Paths" panel -->
                <SETTING><NAME>AlwaysSearchUserPaths</NAME><VALUE>true</VALUE></SETTING>
                <SETTING><NAME>InterpretDOSAndUnixPaths</NAME><VALUE>true</VALUE></SETTING>
                <SETTING><NAME>RequireFrameworkStyleIncludes</NAME><VALUE>false</VALUE></SETTING>
                <SETTING><NAME>SourceRelativeIncludes</NAME><VALUE>false</VALUE></SETTING>
                <SETTING><NAME>UserSearchPaths</NAME>
                    <SETTING>
                        <SETTING><NAME>SearchPath</NAME>
                            <SETTING><NAME>Path</NAME><VALUE></VALUE></SETTING>
                            <SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING>
                            <SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>
                        </SETTING>
                        <SETTING><NAME>Recursive</NAME><VALUE>true</VALUE></SETTING>
                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>
                    </SETTING>
                    <SETTING>
                        <SETTING><NAME>SearchPath</NAME>
                            <SETTING><NAME>Path</NAME><VALUE>:::Source:</VALUE></SETTING>
                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>
                            <SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>
                        </SETTING>
                        <SETTING><NAME>Recursive</NAME><VALUE>true</VALUE></SETTING>
                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>
                    </SETTING>
                    <SETTING>
                        <SETTING><NAME>SearchPath</NAME>
                            <SETTING><NAME>Path</NAME><VALUE>::::SDK:Includes:</VALUE></SETTING>
                            <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>
                            <SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>
                        </SETTING>
                        <SETTING><NAME>Recursive</NAME><VALUE>true</VALUE></SETTING>
                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>
                    </SETTING>
                </SETTING>
                <SETTING><NAME>SystemSearchPaths</NAME>
                    <SETTING>
                        <SETTING><NAME>SearchPath</NAME>
                            <SETTING><NAME>Path</NAME><VALUE>MSL</VALUE></SETTING>
                            <SETTING><NAME>PathFormat</NAME><VALUE>Windows</VALUE></SETTING>
                            <SETTING><NAME>PathRoot</NAME><VALUE>CodeWarrior</VALUE></SETTING>
                        </SETTING>
                        <SETTING><NAME>Recursive</NAME><VALUE>true</VALUE></SETTING>
                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>
                    </SETTING>
                    <SETTING>
                        <SETTING><NAME>SearchPath</NAME>
                            <SETTING><NAME>Path</NAME><VALUE>Win32-x86 Support</VALUE></SETTING>
                            <SETTING><NAME>PathFormat</NAME><VALUE>Unix</VALUE></SETTING>
                            <SETTING><NAME>PathRoot</NAME><VALUE>CodeWarrior</VALUE></SETTING>
                        </SETTING>
                        <SETTING><NAME>Recursive</NAME><VALUE>true</VALUE></SETTING>
                        <SETTING><NAME>FrameworkPath</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>HostFlags</NAME><VALUE>All</VALUE></SETTING>
                    </SETTING>
                </SETTING>

                <!-- Settings for "Debugger Runtime" panel -->
                <SETTING><NAME>MWRuntimeSettings_WorkingDirectory</NAME><VALUE></VALUE></SETTING>
                <SETTING><NAME>MWRuntimeSettings_CommandLine</NAME><VALUE></VALUE></SETTING>
                <SETTING><NAME>MWRuntimeSettings_HostApplication</NAME>
                    <SETTING><NAME>Path</NAME><VALUE></VALUE></SETTING>
                    <SETTING><NAME>PathFormat</NAME><VALUE>Generic</VALUE></SETTING>
                    <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>
                </SETTING>
                <SETTING><NAME>MWRuntimeSettings_EnvVars</NAME><VALUE></VALUE></SETTING>

                <!-- Settings for "Target Settings" panel -->
                <SETTING><NAME>Linker</NAME><VALUE>Win32 x86 Linker</VALUE></SETTING>
                <SETTING><NAME>PreLinker</NAME><VALUE></VALUE></SETTING>
                <SETTING><NAME>PostLinker</NAME><VALUE></VALUE></SETTING>
                <SETTING><NAME>Targetname</NAME><VALUE>Win32 C DLL Debug</VALUE></SETTING>
                <SETTING><NAME>OutputDirectory</NAME>
                    <SETTING><NAME>Path</NAME><VALUE>::::SDK:Libraries:Windows:Debug:</VALUE></SETTING>
                    <SETTING><NAME>PathFormat</NAME><VALUE>MacOS</VALUE></SETTING>
                    <SETTING><NAME>PathRoot</NAME><VALUE>Project</VALUE></SETTING>
                </SETTING>
                <SETTING><NAME>SaveEntriesUsingRelativePaths</NAME><VALUE>false</VALUE></SETTING>

                <!-- Settings for "File Mappings" panel -->
                <SETTING><NAME>FileMappings</NAME>
                    <SETTING>
                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
                        <SETTING><NAME>FileExtension</NAME><VALUE>.c</VALUE></SETTING>
                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ x86</VALUE></SETTING>
                        <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
                    </SETTING>
                    <SETTING>
                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
                        <SETTING><NAME>FileExtension</NAME><VALUE>.c++</VALUE></SETTING>
                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ x86</VALUE></SETTING>
                        <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
                    </SETTING>
                    <SETTING>
                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
                        <SETTING><NAME>FileExtension</NAME><VALUE>.cc</VALUE></SETTING>
                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ x86</VALUE></SETTING>
                        <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
                    </SETTING>
                    <SETTING>
                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
                        <SETTING><NAME>FileExtension</NAME><VALUE>.cp</VALUE></SETTING>
                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ x86</VALUE></SETTING>
                        <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
                    </SETTING>
                    <SETTING>
                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
                        <SETTING><NAME>FileExtension</NAME><VALUE>.cpp</VALUE></SETTING>
                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ x86</VALUE></SETTING>
                        <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
                    </SETTING>
                    <SETTING>
                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
                        <SETTING><NAME>FileExtension</NAME><VALUE>.def</VALUE></SETTING>
                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>
                        <SETTING><NAME>EditLanguage</NAME><VALUE></VALUE></SETTING>
                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
                    </SETTING>
                    <SETTING>
                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
                        <SETTING><NAME>FileExtension</NAME><VALUE>.h</VALUE></SETTING>
                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ x86</VALUE></SETTING>
                        <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING>
                    </SETTING>
                    <SETTING>
                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
                        <SETTING><NAME>FileExtension</NAME><VALUE>.p</VALUE></SETTING>
                        <SETTING><NAME>Compiler</NAME><VALUE>MW Pascal x86</VALUE></SETTING>
                        <SETTING><NAME>EditLanguage</NAME><VALUE></VALUE></SETTING>
                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
                    </SETTING>
                    <SETTING>
                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
                        <SETTING><NAME>FileExtension</NAME><VALUE>.pas</VALUE></SETTING>
                        <SETTING><NAME>Compiler</NAME><VALUE>MW Pascal x86</VALUE></SETTING>
                        <SETTING><NAME>EditLanguage</NAME><VALUE></VALUE></SETTING>
                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
                    </SETTING>
                    <SETTING>
                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
                        <SETTING><NAME>FileExtension</NAME><VALUE>.pch</VALUE></SETTING>
                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ x86</VALUE></SETTING>
                        <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
                        <SETTING><NAME>Precompile</NAME><VALUE>true</VALUE></SETTING>
                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
                    </SETTING>
                    <SETTING>
                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
                        <SETTING><NAME>FileExtension</NAME><VALUE>.pch++</VALUE></SETTING>
                        <SETTING><NAME>Compiler</NAME><VALUE>MW C/C++ x86</VALUE></SETTING>
                        <SETTING><NAME>EditLanguage</NAME><VALUE>C/C++</VALUE></SETTING>
                        <SETTING><NAME>Precompile</NAME><VALUE>true</VALUE></SETTING>
                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
                    </SETTING>
                    <SETTING>
                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
                        <SETTING><NAME>FileExtension</NAME><VALUE>.ppu</VALUE></SETTING>
                        <SETTING><NAME>Compiler</NAME><VALUE>MW Pascal x86</VALUE></SETTING>
                        <SETTING><NAME>EditLanguage</NAME><VALUE></VALUE></SETTING>
                        <SETTING><NAME>Precompile</NAME><VALUE>true</VALUE></SETTING>
                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
                    </SETTING>
                    <SETTING>
                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
                        <SETTING><NAME>FileExtension</NAME><VALUE>.rc</VALUE></SETTING>
                        <SETTING><NAME>Compiler</NAME><VALUE>MW WinRC</VALUE></SETTING>
                        <SETTING><NAME>EditLanguage</NAME><VALUE></VALUE></SETTING>
                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
                    </SETTING>
                    <SETTING>
                        <SETTING><NAME>FileType</NAME><VALUE>TEXT</VALUE></SETTING>
                        <SETTING><NAME>FileExtension</NAME><VALUE>.res</VALUE></SETTING>
                        <SETTING><NAME>Compiler</NAME><VALUE>WinRes Import</VALUE></SETTING>
                        <SETTING><NAME>EditLanguage</NAME><VALUE></VALUE></SETTING>
                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
                    </SETTING>
                    <SETTING>
                        <SETTING><NAME>FileExtension</NAME><VALUE>.doc</VALUE></SETTING>
                        <SETTING><NAME>Compiler</NAME><VALUE></VALUE></SETTING>
                        <SETTING><NAME>EditLanguage</NAME><VALUE></VALUE></SETTING>
                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>Launchable</NAME><VALUE>true</VALUE></SETTING>
                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>true</VALUE></SETTING>
                    </SETTING>
                    <SETTING>
                        <SETTING><NAME>FileExtension</NAME><VALUE>.lib</VALUE></SETTING>
                        <SETTING><NAME>Compiler</NAME><VALUE>Lib Import x86</VALUE></SETTING>
                        <SETTING><NAME>EditLanguage</NAME><VALUE></VALUE></SETTING>
                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
                    </SETTING>
                    <SETTING>
                        <SETTING><NAME>FileExtension</NAME><VALUE>.obj</VALUE></SETTING>
                        <SETTING><NAME>Compiler</NAME><VALUE>Obj Import x86</VALUE></SETTING>
                        <SETTING><NAME>EditLanguage</NAME><VALUE></VALUE></SETTING>
                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
                    </SETTING>
                    <SETTING>
                        <SETTING><NAME>FileExtension</NAME><VALUE>.res</VALUE></SETTING>
                        <SETTING><NAME>Compiler</NAME><VALUE>WinRes Import</VALUE></SETTING>
                        <SETTING><NAME>EditLanguage</NAME><VALUE></VALUE></SETTING>
                        <SETTING><NAME>Precompile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>Launchable</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>ResourceFile</NAME><VALUE>false</VALUE></SETTING>
                        <SETTING><NAME>IgnoredByMake</NAME><VALUE>false</VALUE></SETTING>
                    </SETTING>
                </SETTING>

                <!-- Settings for "Build Extras" panel -->
                <SETTING><NAME>CacheModDates</NAME><VALUE>true</VALUE></SETTING>
                <SETTING><NAME>DumpBrowserInfo</NAME><VALUE>false</VALUE></SETTING>
                <SETTING><NAME>CacheSubprojects</NAME><VALUE>true</VALUE></SETTING>
                <SETTING><NAME>UseThirdPartyDebugger</NAME><VALUE>false</VALUE></SETTING>
                <SETTING><NAME>BrowserGenerator</NAME><VALUE>1</VALUE></SETTING>
                <SETTING><NAME>DebuggerAppPath</NAME>
                    <SETTING><NAME>Path</NAME><VALUE></VALUE></SETTING>
                    <SETTING><NAME>PathFormat</NAME><VALUE>Generic</VALUE></SETTING>
                    <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>
                </SETTING>
                <SETTING><NAME>DebuggerCmdLineArgs</NAME><VALUE></VALUE></SETTING>
                <SETTING><NAME>DebuggerWorkingDir</NAME>
                    <SETTING><NAME>Path</NAME><VALUE></VALUE></SETTING>
                    <SETTING><NAME>PathFormat</NAME><VALUE>Generic</VALUE></SETTING>
                    <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>
                </SETTING>
                <SETTING><NAME>CodeCompletionPrefixFileName</NAME><VALUE>Win32Headers.pch</VALUE></SETTING>
                <SETTING><NAME>CodeCompletionMacroFileName</NAME><VALUE>Win32_C++_Macros.h</VALUE></SETTING>

                <!-- Settings for "Debugger Target" panel -->
                <SETTING><NAME>ConsoleEncoding</NAME><VALUE>0</VALUE></SETTING>
                <SETTING><NAME>LogSystemMessages</NAME><VALUE>false</VALUE></SETTING>
                <SETTING><NAME>AutoTargetDLLsPopUp</NAME><VALUE>0</VALUE></SETTING>
                <SETTING><NAME>StopAtWatchpoints</NAME><VALUE>true</VALUE></SETTING>
                <SETTING><NAME>PauseWhileRunning</NAME><VALUE>false</VALUE></SETTING>
                <SETTING><NAME>PauseInterval</NAME><VALUE>5</VALUE></SETTING>
                <SETTING><NAME>PauseUIFlags</NAME><VALUE>0</VALUE></SETTING>
                <SETTING><NAME>AltExePath</NAME>
                    <SETTING><NAME>Path</NAME><VALUE></VALUE></SETTING>
                    <SETTING><NAME>PathFormat</NAME><VALUE>Unix</VALUE></SETTING>
                    <SETTING><NAME>PathRoot</NAME><VALUE>Absolute</VALUE></SETTING>
                </SETTING>
                <SETTING><NAME>StopAtTempBPOnLaunch</NAME><VALUE>true</VALUE></SETTING>
                <SETTING><NAME>CacheSymbolics</NAME><VALUE>true</VALUE></SETTING>
                <SETTING><NAME>TempBPFunctionName</NAME><VALUE>main</VALUE></SETTING>
                <SETTING><NAME>TempBPType</NAME><VALUE>0</VALUE></SETTING>

                <!-- Settings for "Remote Debug" panel -->
                <SETTING><NAME>Enabled</NAME><VALUE>false</VALUE></SETTING>
                <SETTING><NAME>ConnectionName</NAME><VALUE>Dell</VALUE></SETTING>
                <SETTING><NAME>DownloadPath</NAME><VALUE></VALUE></SETTING>
                <SETTING><NAME>LaunchRemoteApp</NAME><VALUE>true</VALUE></SETTING>
                <SETTING><NAME>RemoteAppPath</NAME><VALUE></VALUE></SETTING>
                <SETTING><NAME>CoreID</NAME><VALUE>0</VALUE></SETTING>
                <SETTING><NAME>JTAGClockSpeed</NAME><VALUE>8000</VALUE></SETTING>
                <SETTING><NAME>IsMultiCore</NAME><VALUE>false</VALUE></SETTING>
                <SETTING><NAME>OSDownload</NAME><VALUE>false</VALUE></SETTING>
                <SETTING><NAME>UseGlobalOSDownload</NAME><VALUE>false</VALUE></SETTING>
                <SETTING><NAME>OSDownloadConnectionName</NAME><VALUE></VALUE></SETTING>
                <SETTING><NAME>OSDownloadPath</NAME><VALUE></VALUE></SETTING>
                <SETTING><NAME>AltDownload</NAME><VALUE>false</VALUE></SETTING>
                <SETTING><NAME>AltDownloadConnectionName</NAME><VALUE></VALUE></SETTING>

                <!-- Settings for "Auto-target" panel -->
                <SETTING><NAME>OtherExecutables</NAME><VALUE></VALUE></SETTING>

                <!-- Settings for "Analyzer Connections" panel -->
                <SETTING><NAME>AnalyzerConnectionName</NAME><VALUE></VALUE></SETTING>

                <!-- Settings for "Custom Keywords" panel -->
                <SETTING><NAME>CustomColor1</NAME>
                    <SETTING><NAME>Red</NAME><VALUE>0</VALUE></SETTING>
                    <SETTING><NAME>Green</NAME><VALUE>32767</VALUE></SETTING>
                    <SETTING><NAME>Blue</NAME><VALUE>0</VALUE></SETTING>
                </SETTING>
                <SETTING><NAME>CustomColor2</NAME>
                    <SETTING><NAME>Red</NAME><VALUE>0</VALUE></SETTING>
                    <SETTING><NAME>Green</NAME><VALUE>32767</VALUE></SETTING>
                    <SETTING><NAME>Blue</NAME><VALUE>0</VALUE></SETTING>
                </SETTING>
                <SETTING><NAME>CustomColor3</NAME>
                    <SETTING><NAME>Red</NAME><VALUE>0</VALUE></SETTING>
                    <SETTING><NAME>Green</NAME><VALUE>32767</VALUE></SETTING>
                    <SETTING><NAME>Blue</NAME><VALUE>0</VALUE></SETTING>
                </SETTING>
                <SETTING><NAME>CustomColor4</NAME>
                    <SETTING><NAME>Red</NAME><VALUE>0</VALUE></SETTING>
                    <SETTING><NAME>Green</NAME><VALUE>32767</VALUE></SETTING>
                    <SETTING><NAME>Blue</NAME><VALUE>0</VALUE></SETTING>
                </SETTING>

                <!-- Settings for "Checksum Panel" panel -->
                <SETTING><NAME>Algorithm</NAME><VALUE>2</VALUE></SETTING>
                <SETTING><NAME>ResourceTypesToCheck</NAME><VALUE>'PPob', 'cfrg', 'DITL', 'DLOG', 'ALRT', 'vers', 'CODE'</VALUE></SETTING>
                <SETTING><NAME>ExtraData</NAME><VALUE></VALUE></SETTING>
                <SETTING><NAME>ResultType</NAME><VALUE>Chkx</VALUE></SETTING>
                <SETTING><NAME>ResultID</NAME><VALUE>128</VALUE></SETTING>
                <SETTING><NAME>AddBuildDate</NAME><VALUE>-1</VALUE></SETTING>
                <SETTING><NAME>SetBundleBit</NAME><VALUE>true</VALUE></SETTING>
                <SETTING><NAME>ChecksumPEFMode</NAME><VALUE>true</VALUE></SETTING>

                <!-- Settings for "C/C++ Compiler" panel -->
                <SETTING><NAME>MWFrontEnd_C_cplusplus</NAME><VALUE>1</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_checkprotos</NAME><VALUE>1</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_arm</NAME><VALUE>0</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_trigraphs</NAME><VALUE>0</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_onlystdkeywords</NAME><VALUE>0</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_enumsalwaysint</NAME><VALUE>1</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_ansistrict</NAME><VALUE>0</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_wchar_type</NAME><VALUE>1</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_enableexceptions</NAME><VALUE>1</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_dontreusestrings</NAME><VALUE>0</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_poolstrings</NAME><VALUE>0</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_dontinline</NAME><VALUE>1</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_useRTTI</NAME><VALUE>0</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_unsignedchars</NAME><VALUE>0</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_autoinline</NAME><VALUE>0</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_booltruefalse</NAME><VALUE>1</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_inlinelevel</NAME><VALUE>0</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_ecplusplus</NAME><VALUE>0</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_defer_codegen</NAME><VALUE>0</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_templateparser</NAME><VALUE>1</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_c99</NAME><VALUE>0</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_bottomupinline</NAME><VALUE>1</VALUE></SETTING>
                <SETTING><NAME>MWFrontEnd_C_gcc_extensions</NAME><VALUE>0</VALUE></SETTING>